services:
    semaphore:
        #ports:
        #    - 3000:3000
        image: semaphoreui/semaphore:v2.12.14
        environment:
            SEMAPHORE_DB_DIALECT: bolt
            SEMAPHORE_ADMIN: ${admin}
            SEMAPHORE_ADMIN_PASSWORD: ${adminpass}
            SEMAPHORE_ADMIN_NAME: Admin
            SEMAPHORE_ADMIN_EMAIL: admin@localhost
        cpus: 0.50
        mem_limit: 512M
        network_mode: host
