---
- name: Redis
  hosts: redis
  tasks:
  - name: Download & Install
    shell: |
      mkdir -p /tmp/download ; cd /tmp/download
      wget https://download.redis.io/releases/redis-{{ redis_version }}.tar.gz
      tar -xf redis-{{ redis_version }}.tar.gz
      cd redis-{{ redis_version }}
      make PREFIX=/opt/{{ prefix }} install
      mkdir -p /opt/{{ prefix }}/conf
      mkdir -p /data/{{ prefix }}; chown -R detik.detik /data/{{ prefix }}
      mkdir -p /var/log/{{ prefix }}; chown -R detik.detik /var/log/{{ prefix }}

  - name: Clean
    shell: |
      rm -rf /tmp/download
