---
- name: systemcontrol
  hosts: sysctl
  tasks:
  - name: Ulimit User
    shell: |
      cat /etc/redhat-release | grep -o "7.9" > /tmp/osversion
      osversion=$(cat /tmp/osversion | grep -o "7")
      if [ "$osversion" == '7' ]; then
         sed -i -e 's/4096/65535/g' /etc/security/limits.d/20-nproc.conf
      else
         sed -i -e 's/4096/65535/g' /etc/security/limits.d/90-nproc.conf
      fi;
      rm -rf /tmp/osversion

  - name: Ulimit Global
    shell: |
      sed -i -e 's/4096/65535/g' /etc/security/limits.conf

  - name: System Control
    shell: |
      cat > /etc/sysctl.conf<<EOF
      vm.swappiness = 0
      kernel.sysrq = 1

      net.ipv4.neigh.default.gc_stale_time = 120

      net.ipv4.conf.all.rp_filter = 0
      net.ipv4.conf.default.rp_filter = 0
      net.ipv4.conf.default.arp_announce = 2
      net.ipv4.conf.lo.arp_announce = 2
      net.ipv4.conf.all.arp_announce = 2

      net.ipv4.tcp_max_tw_buckets = 10000
      net.ipv4.tcp_syncookies = 1
      net.ipv4.tcp_max_syn_backlog = 1024
      net.ipv4.tcp_synack_retries = 2
      net.ipv4.tcp_slow_start_after_idle = 0

      net.ipv4.ip_local_port_range = 1024 65535
      net.core.netdev_max_backlog = 65535
      net.ipv4.tcp_max_syn_backlog = 65535
      net.core.somaxconn = 65535
      EOF
